apiVersion: v1
kind: ConfigMap
metadata:
  name: "spring-petclinic-configmap"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: {{ .Values.name }}
data:
  application.properties: |-
    name=configmap
