apiVersion: v1
kind: ConfigMap
metadata:
  name: "spring-petclinic-configmap"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: {{- include "spring-petclinic.labels" . | nindent 4 }}
data:
  application.properties: |-
    name=configmap
